#!/bin/bash
swaylock -i ~/Pictures/wallpaper/moebius_canyon.jpg \
  --indicator-radius 20  \
  --indicator-thickness 5  \
  --text-ver-color 00000000 \
  --text-clear-color 00000000 \
  --text-wrong-color 00000000 \
  -r 
