#!/bin/bash

# Launch Rofi
rofi -no-lazy-grab -show drun \
-display-drun "apps" -drun-display-format "{name}" \
-display-ssh "ssh" \
-hide-scrollbar true \
-bw 0 \
-lines 10 \
-line-padding 10 \
-padding 20 \
-width 30 \
-xoffset 8 -yoffset 32 \
-location 1 \
-columns 2 \
-show-icons -icon-theme "Papirus" \
-font "Ubuntu Condensed 10" \
-theme $HOME/.config/rofi/menu.rasi

