[module/music]
type = custom/script
interval = 1
format-prefix = " "
format = <label>
exec = python3 $HOME/.config/polybar/scripts/music_status.py -f '{artist} -- {song}' -s 30

[module/taskwarrior]
interval = 30
type = custom/script
exec = $HOME/.config/polybar/scripts/task_polybar.sh
format = <label>
format-foreground = #FFF
format-prefix = " "
click-left = task "$((`cat /tmp/tw_polybar_id`))" done


[module/lang]
type = custom/script
interval = 1
exec =  $HOME/.config/polybar/scripts/lang.sh
click-left = kb_switch


[module/powermenu]
type = custom/menu

format-spacing = 1
# Font awesome power off icon
label-open = 
label-open-foreground = ${colors.foreground-alt}
label-close =  cancel
label-close-foreground = ${colors.foreground-alt}
label-separator = |
label-separator-foreground = ${colors.foreground-alt}

menu-0-0 = logout
menu-0-1 = power
menu-0-0-exec = menu-open-1
menu-0-1-exec = menu-open-2

menu-1-0 = logout
menu-1-0-exec = i3-msg exit

menu-2-0 = reboot
menu-2-1 = shutdown
menu-2-0-exec = menu-open-3
menu-2-1-exec = menu-open-4

menu-3-0 = reboot
menu-3-0-exec =  reboot

menu-4-0 = shutdown
menu-4-0-exec = shutdown -h now

; vim:ft=dosini
