[module/previous]
type = custom/script
interval = 86400
format = "%{T3}<label>"
format-padding = 5
exec=echo ""
exec-if="pgrep mpd  || pgrep spotify"
format-underline = #1db954
line-size = 1
click-left="$HOME/.config/polybar/scripts/music_control.py previous"

[module/previous]
type = custom/script
interval = 86400
format = "%{T3}<label>"
format-padding = 5
exec=echo ""
exec-if="pgrep mpd  || pgrep spotify"
format-underline = #1db954
line-size = 1
click-left="$HOME/.config/polybar/scripts/music_control.py next"

[module/playpause]
type=custom/ipc
; Default
hook-0=echo ""
; Playing
hook-1=echo ""
; Paused
hook-2=echo ""
initial=1
format-underline=#1db954
line-size=1
click-left="$HOME/.config/polybar/scripts/music_control.py playpause"

[module/music_status]
type=custom/ipc
hook-0=echo ""
hook-1=python3


