;=:= Modules ========================================================

[module/menu]
type = custom/text
content = 
alt-icon = 
content-padding = 2
content-background = ${color.acolor}
content-foreground = ${color.fg}
click-left = $HOME/.config/polybar/scripts/menu
click-right = $HOME/.config/polybar/scripts/color-switch.sh

[module/term]
type = custom/text
content = 
content-foreground = ${color.fg-alt}
click-left = random_floating_term.py &
click-right = alacritty &

[module/files]
type = custom/text
content = 
content-padding = 1
content-foreground = ${color.fg-alt}
click-left = thunar &

[module/browser]
type = custom/text
content = 
content-padding = 1
content-foreground = ${color.fg-alt}
click-left = firefox &

[module/spotify]
type = custom/text
content = 
content-padding = 1
content-foreground = ${color.fg-alt}
click-left = spotify &

[module/music]
type = custom/script
interval = 1
format-prefix = ""
format = <label>
fixed-center = true
exec = python3 $HOME/.config/polybar/scripts/music_status.py -f '{artist} -- {song}' -s 30

[module/wifi]
type = internal/network
interface = wlp59s0
interval = 10
format-connected = <label-connected>
label-connected =  %essid%

[module/eth]
type = internal/network
interface = enx00e04c001dec
interval = 10
format-connected-foreground = ${color.fg-alt}
label-connected =  %local_ip%


[module/date]
type = internal/date
interval = 30
label =  %time%
time =  %I:%M %p%
time-alt =  %Y-%m-%d  %I:%M %p%


[module/powermenu]
type = custom/menu
format-spacing = 1
label-open = 
label-open-background = ${color.acolor}
content-open-foreground = ${color.fg}
label-separator = |

menu-0-0 = logout
menu-0-1 = power
menu-0-0-exec = menu-open-1
menu-0-1-exec = menu-open-2

menu-1-0 = logout
menu-1-0-exec = i3-msg exit

menu-2-0 = reboot
menu-2-1 = shutdown
menu-2-0-exec = menu-open-3
menu-2-1-exec = menu-open-4

menu-3-0 = reboot
menu-3-0-exec =  reboot

menu-4-0 = shutdown
menu-4-0-exec = shutdown -h now



;== EOF ========================================================
