;== Modules ========================================================
[module/filesystem]
type = internal/fs
interval = 60
mount-0 = /

label-mounted =  %percentage_used%%
label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${color.ug}

[module/workspaces]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = false

; Only show workspaces on the same output as the bar
pin-workspaces = true

label-mode-padding = 2
label-mode-foreground = #000
label-mode-background = ${color.bg}

; focused = Active workspace on focused monitor
label-focused = %index%
label-focused-background = ${color.mf}
label-focused-padding = 2

; unfocused = Inactive workspace on any monitor
label-unfocused = %index%
label-unfocused-padding = 2

; visible = Active workspace on unfocused monitor
label-visible = %index%
label-visible-background = ${color.bg}
label-visible-padding = ${color.ac}

; urgent = Workspace with urgency hint set
label-urgent = %index%
label-urgent-background = ${color.ug}
label-urgent-padding = ${color.ug}

ws-icon-0 = 1;
ws-icon-1 = 2;
ws-icon-2 = 3;
ws-icon-3 = 4;
ws-icon-4 = 5;
ws-icon-5 = 6;
ws-icon-6 = 7;
ws-icon-7 = 8;
ws-icon-8 = 9;
ws-icon-9 = 10;

ws-icon-default = 


;==========================================================

[module/mpd]
type = internal/mpd
;format-online = <toggle> <label-song>
format-online =  <label-song>

icon-play = 
icon-pause = 

label-song-maxlen = 25
label-song-ellipsis = true

;==========================================================

[module/battery]
type = internal/battery
full-at = 99
time-format = %H:%M
battery = BAT0
adapter = AC
format-charging = <animation-charging> <label-charging>
;label-charging = %percentage%% (%time%)
label-charging = %percentage%%
format-discharging = <ramp-capacity> <label-discharging>
;label-discharging = %percentage%% (%time%)
label-discharging = %percentage%%
format-full = <label-full>

format-full-prefix = " "
ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 

ramp-capacity-1-foreground = ${color.red}
ramp-capacity-2-foreground = ${color.yellow}
ramp-capacity-3-foreground = ${color.yellow}
ramp-capacity-4-foreground   = ${color.light-green}
ramp-capacity-5-foreground   = ${color.light-green}
ramp-capacity-6-foreground   = ${color.green}

bar-capacity-width = 10

animation-charging-0 = ""
animation-charging-1 = ""
animation-charging-2 = ""
animation-charging-3 = ""
animation-charging-4 = ""

animation-charging-framerate = 750

[module/volume]
type = internal/pulseaudio
;speaker-mixer = Speaker
;headphone-mixer = Headphone
;headphone-id = 16
;mapped = true
format-volume = <ramp-volume> <label-volume>
label-volume = %percentage%%
format-muted-prefix = " "
label-muted = MUTE

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 
ramp-volume-3 = 
ramp-volume-4 = 
ramp-volume-5 = 
ramp-volume-6 = 

[module/cpu]
type = internal/cpu
interval = 2
;format = <label> <ramp-coreload>
label =  %percentage%%

[module/memory]
type = internal/memory
interval = 2
label =   %percentage_used%%

[module/temperature]
type = internal/temperature
interval = 2
label =  %temperature-c%
units = true
hwmon-path = /sys/devices/platform/coretemp.0/hwmon/hwmon4/temp1_input
;== EOF ========================================================
